version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run: echo "A first hello"

  test:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: bundle install
          no_output_timeout: 15m
          command:
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - restore_cache:
          key: taskleaf-{{ checksum "Gemfile.lock" }}
      - save_cache:
          key: taskleaf-{{ checksum "Gemfile.lock" }}
          paths:
            - ".git"
